### ISSUE TITLE
Consider adding requested approval to `SwapToken` struct

### ISSUE THREAD

**Issue by fleupold** [meetmangukiya/cow-fee#10]
Currently, for new tokens, two calls need to be issued to sell a token

1. [COWFeeModule::approve](https://github.com/meetmangukiya/cow-fee/blob/main/src/COWFeeModule.sol)
2. [COWFeeModule::drip](https://github.com/meetmangukiya/cow-fee/blob/main/src/COWFeeModule.sol)

Has it been considered to combine the two and set an optional allowance field on the `SwapToken` struct (which would be 0 bytes in case the contract already has allowance)?

**Comment by meetmangukiya** [comment]
Yeah, can move it, but will be a lot of wasted calldata every time.

**Comment by meetmangukiya** [comment]
Added a separate argument for approvals instead, so as to not increase the calldata size for each SwapToken.
