### ISSUE TITLE
Reduce order validity period

### ISSUE THREAD

**Issue by fedgiac** [meetmangukiya/cow-fee#2]
Orders created from the module have a validity period of up to a year.
This is extremely high and it means that during a year the settlement contract accumulates a large amount of open orders.
There's also both a maximum validity period and a maximum number of open orders enforced by the API, both of which could cause issues with the script's execution.
It's also bad for accounting as it makes it harder to associate incoming WETH to the time period when this fee was generated.
I'd suggest a validity of about one hour, since any order that's still open after one hour is likely not going to be matched after that.

**Comment by meetmangukiya** [comment]
Will snap it to next to next hour, should make the expiry somewhere between 1-2 hours.
