### ISSUE TITLE
Use past `Trade` events for fetching the list of token balances

### ISSUE THREAD

**Issue by fleupold** [meetmangukiya/cow-fee#8]
Currently `ethplorer` and `blockscout` are used to fetch the list of tokens the settlement contract has balances in (to decide which sell orders to place).

While this works great for mainnet and Gnosis Chain, relying on these external APIs is a liability and makes this project potentially less usable on new chains.

One approach we discussed in the past is to simply filter on past `Trade` events and extract a list of `sellToken` and `buyToken` that could potentially have accrued buffers and use this as a starting point.

In practice, we should probably define a "lookback period" for the range of `Trade` events to fetch.

**Comment by meetmangukiya** [comment]
I think we can just use the subgraph `Token` entity, grab all and check the balances for each. They are created in `handleTrade` https://github.com/cowprotocol/subgraph/blob/d48bf1d5ad6030e41c3ab0f97333b689e43d77f8/src/mapping.ts#L57-L58

**Comment by meetmangukiya** [comment]
I can only find the mainnet instance, not gnosis chain instance. And mainnet instance hasn't been indexing since a month. Can you guys ping someone internally to look into it?

**Comment by fleupold** [comment]
This coincides with the publicly hosted graph service shutting down (we haven't prioritised hosting our own yet). Would it be possible to use the indexing approach with a user specifiable lookback block range?
