### ISSUE TITLE
Allow specifying a minBuy Amount

### ISSUE THREAD

**Issue by fleupold** [meetmangukiya/cow-fee#9]
While we can theoretically trust CoW Protocol to find the best possible execution, it might make sense for parity with the current withdraw script to allow specifying a limit price for the withdrawl (which can be set to 1 wei to achieve the current behavior).

In practice, I'd expect the user to specify a slippage tolerance and use the quoted price - that slippage tolerance as `minBuy`

**Comment by mfw78** [comment]
Is quoted price in this context relative to that determined by the quote endpoint on CoW's `/quote` endpoint?

**Comment by meetmangukiya** [comment]
Do you mean about the 1 wei set as minimum out on the order?

**Comment by mfw78** [comment]
> Do you mean about the 1 wei set as minimum out on the order?

From my understanding of this, this would refer to each pair gets a quote from the `/quote` endpoint, and then applies a configurable amount of slippage, such that the `buyAmount` would then be specified within the `calldata`.
